[package]
name = "sunoto-daemon"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sunoto-audio = { path = "../../crates/sunoto-audio" }
sunoto-core = { path = "../../crates/sunoto-core" }
sunoto-ipc = { path = "../../crates/sunoto-ipc" }
sunoto-linux = { path = "../../crates/sunoto-linux" }
sunoto-polish = { path = "../../crates/sunoto-polish" }
